### ISSUE TITLE
Missing OUR-I.URDF and/or OUR-II.URDF

### ISSUE THREAD

**Issue by AkosTar** [LMNcnu/OUR_6DoFs#2]
The Smokie robot URDF for MoveIt is not found.

But the tutorial says that this is exist, without this file MoveIt can not be used.
http://wiki.ros.org/Robots/OUR/MoveIt%20Setup%20Assistant%20for%20OUR%20robot

**Comment by LMNcnu** [comment]
I have added the URDF in the our_model fold.

**Comment by AkosTar** [comment]
Thank you very much!
