### ISSUE TITLE
API - Using with ethernet interface

### ISSUE THREAD

**Issue by Joska213** [LMNcnu/OUR_6DoFs#4]
Is your API can be used with ethernet intarface of your OUR robot, or it is just for CAN interface?
If it works only with CAN interface please could you provide an API extension that can use Ethernet interface?

**Comment by LMNcnu** [comment]
The API can't be used with Ethernet interface, but the API for EtherCat interface is being developed.
So, it's just for CAN interface now.

**Comment by Joska213** [comment]
Thank you for the answer! I have another one though: do you have any sample code about using your IK library?
