### ISSUE TITLE
Speed mode

### ISSUE THREAD

**Issue by Joska213** [LMNcnu/OUR_6DoFs#5]
I cannot find speed control so I have a question: Is it possible to control OUR robot by speed not by radians (or angles) with your API?

**Comment by LMNcnu** [comment]
The API can't control OUR robot by speed.The driver for OUR robot has already set up the speed parameter.

**Comment by Joska213** [comment]
I see. So the only API function that I can use is JointControlCanBus::setTagPosRadio or JointControlCanBus::setTagPosAngle to control the robot's position?

**Comment by LMNcnu** [comment]
Yes

**Comment by Joska213** [comment]
Thank you!
