### ISSUE TITLE
Best way to achieve smooth moving using your API

### ISSUE THREAD

**Issue by Joska213** [LMNcnu/OUR_6DoFs#6]
Hi,
I have a question about your API again: what is the best way to achieve smooth moving by using your API? 
I try to use ROS and rviz, so rviz generates the trajectory (joint) points for me and I send them to OUR robot by using the API's setTagPosRadio function. In this case the robot starts to move, reach the given point and stops and this is repeated as many times as many points in the trajectory, so the move is not smooth but erratic. Is there a way to achieve smooth moving as seen in your program controller application ORPE?

**Comment by LMNcnu** [comment]
You can reference  OUR_6DoFs/our_robot/kdl_rviz/src/kdl_rviz.cpp.It has already achieved the function of controlling the OUR robot move to a goal position from the home position. 
Details:
            1.set the goal position.
            2.generate the trajectory by the plan() function.
            3.send the the trajectory (joint) points to the topic "moveJ" in the our_basic/joint_control node(just use the  setTagPosRadio function).
           4.The real OUR robot will move smoothly.
